sonar.organization=fazy777
sonar.projectKey=fazy777_cohort-9-java-15749-muhammad

# Define test directories
sonar.tests=Frontend/contact_managment_system/test,Backend/contact_managment_system/main_application/src/test/java

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
sonar.cpd.exclusions=**/test/**,**/src/test/**,**/*.test.js
